name: Pipeline de Despliegue VM local (Prueba)

on:
  push:
    branches: ["main"]

jobs:
  despliegue:
    name: Compilar y Desplegar en Servidor
    runs-on: vps-local

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - run: |
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" > .env
          echo "NAME_DB"=${{ secrets.NAME_DB }} >> .env

      - run: docker compose up -d --build
