name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26.1"

      - run: go mod download
      - run: go test -v ./...

      - name: Railway CLI
        run: npm install -g @railway/cli

      - name: Deployment
        run: railway up --detach --service ci-cd
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
